### ISSUE TITLE
[Feature] Run the Action in a branch other than the main branch.

### ISSUE THREAD

**Issue by TheAlbertDev** [skills/action-update-step#4]
Currently, the Action only runs on the `main` branch. Would it be possible to make it run in other branches by giving its name as input?

**Comment by heiskr** [comment]
Apologies for the very slow response cycle. I'd like more context on the need for this change, what would this enable? Thanks :)

**Comment by TheAlbertDev** [comment]
With the proposed changes, the Action is still performed on the default `main` branch, but a branch with a different name can be optionally configured. Examples of use, localised branch names (in Spanish `main` would be `principal`), branch names for different localisations (if the course has different languages, each language can be in the branch `main/en`, `main/en`, `main/cat`, etc.), internal policies of an organisation (maybe the main is called `supermain`), etc.

**Comment by heiskr** [comment]
Hmm, thank you for the context. A team member recommended looking up the default branch with
`gh repo view --json defaultBranchRef --jq ".defaultBranchRef.name"`

Would that address the issue? Or would we still need configuration?

**Comment by TheAlbertDev** [comment]
If the default branch is the Action's target branch, it might work. But in cases like the ones I have discussed where there may be more than one branch of interest (multi-language courses) or where the branch of interest is not the default (monorepo), it would not be a feasible solution. The PR's solution offers a way to increase the configurability of the Action without altering its functionality (none breaking change).
